<?php
namespace app\epiiadmin\controller;

use think\Db;
use think\facade\Config;
use think\facade\Env;
use wslibs\i\epiiadmin\ILeftAndTopData;

/**
 * Created by PhpStorm.
 * User: mrren
 * Date: 2018/6/29
 * Time: 上午10:43
 */
class EpiiController extends \think\Controller
{
    public function fetchNoLayout($template = '', $vars = [], $config = [])
    {
        $this->assign("title", Config::get("app_name"));
        $this->view->engine->layout(false);
        return parent::fetch($template, $vars, $config);
    }

    public function fetch($template = '', $vars = [], $config = [])
    {
        $this->assign("title", Config::get("app_name"));
        return parent::fetch($template, $vars, $config); // TODO: Change the autogenerated stub
    }

    public function jsArgs($dataOrKey = null, $value = null)
    {
        if ($dataOrKey == null) {
            return $this->app->js_args;
        }
        if (is_string($dataOrKey)) {
            if (is_null($value)) {
                return $this->app->js_args[$dataOrKey];
            } else {
                $this->app->js_args[$dataOrKey] = $value;
            }
        }
        if (is_array($dataOrKey)) {
            $this->app->js_args->setData($dataOrKey);
        }
        return $this->app->js_args;
    }

    public function jsAppName($pathtoname = null)
    {
        return $this->jsArgs("appName", $pathtoname);
    }

    /**
     * @param ILeftAndTopData $dataProvider
     * @return mixed
     */
    public function showTopWindow(ILeftAndTopData $dataProvider)
    {
        bind("wslibs\\i\\epiiadmin\\ILeftAndTopData", $dataProvider);//,//需要用户自行修改)

        Config::set("app_theme", $dataProvider->getTheme());
        Config::set("app_left_theme", $dataProvider->getLeftMenuTheme());
        $this->jsArgs("isTop", 1);
        return $this->fetchNoLayout("epiiadmin@index/index");
    }

    public function tableJsonData($table_name,$where,callable $row_callback = null)
    {
        $count = Db::name($table_name)->where($where)->count();
        $list = Db::name($table_name)->where($where)->limit($this->request->param("offset"),$this->request->param("limit"))->select();
        return json(["rows" =>$row_callback?array_map($row_callback,$list):$list, "total" => $count]);
    }




}